### ISSUE TITLE
Access transform object from services

### ISSUE THREAD

**Issue by liamsir** [rhwilr/adonis-bumblebee#34]
Hi!

I'm not being able to see any documentation on how I can access 'transform' instance outside controller. Is such a thing bad design choice, or is there any way that I can do that.

I have an ProductController and a ProductService, instead of transforming data in controller I would like to be able to use transform object inside service, something like this
`const transform = use('Transform')`
and then do the transformation.

Thanks :)

**Comment by liamsir** [comment]
```js
const Bumblebee = use('Adonis/Addons/Bumblebee')
const transformer = Bumblebee.create()
```
I managed to use 'Bumblebee' provider, but I don't want to use .create() in all of my services. Is it good solution to create new custom provider that would abstract 'Bumblebee'?

**Comment by rhwilr** [comment]
Yes, the `create()` method is the correct way to instantiate Bumblebee.
It is mentioned in the documentation just as a [side-note at the end](https://github.com/rhwilr/adonis-bumblebee#fluent-interface) since most people will probably use it in a controller.

The `transform` property in the controller is just a helper that was created with the `create()` [method](https://github.com/rhwilr/adonis-bumblebee/blob/master/providers/BumblebeeProvider.js#L45)

You can create a custom provider or helper to make it more convenient for your use case.
